services:
  webinar-test:
    container_name: webinar-tst
    image: mkovdk/webinar-test
    environment:
       - HOSTNAME=172.17.0.3
       - DATABASE=webinar
       - USERNAME=test
       - PASSWORD=test

# "scale:" option for version 3 https://github.com/docker/compose/issues/5586
    deploy:
      replicas: 0
