- hosts: localhost
  vars:
  - IMAGE: mkovdk/webinar-test
  - PROJECT_NAME: webinar-test
  gather_facts: no
  tasks:
  - name: Docker Compose image from Docker Hub
    community.docker.docker_compose:
      project_name: "{{PROJECT_NAME}}"
      definition:
        version: '3'
        services:
          webinar-test:
            image: "{{IMAGE}}"
#            env_file:
#                - /tmp/my.env
#      scale:
#        test: 2
